/**
 * Career Module Index
 * Exports all career-related systems for owner personality and management
 */

// Owner Personality Engine
export {
  MarketSize,
  TeamContext,
  PersonalityArchetype,
  OwnerGenerationOptions,
  OwnerPersonalitySummary,
  selectArchetypeFromContext,
  generateOwnerTraits,
  generateSecondaryTraits,
  generateInterventionTriggers,
  generateOwnerPersonality,
  generateNetWorth,
  generateOwnerHistory,
  generateOwner,
  getOwnerPersonalitySummary,
  getArchetypeDescription,
} from './OwnerPersonalityEngine';

// Interference System
export {
  TeamState,
  InterventionTrigger,
  ComplianceRecord,
  InterferenceConsequence,
  InterferenceState,
  createInterferenceState,
  detectLosingStreakIntervention,
  detectFanApprovalIntervention,
  detectMediaScrutinyIntervention,
  detectSeasonPerformanceIntervention,
  detectEgoIntervention,
  detectAllInterventions,
  getMostSevereTrigger,
  recordCompliance,
  recordDefiance,
  trackNewDemand,
  calculateComplianceConsequence,
  calculateDefianceConsequence,
  checkExpiredDemands,
  applyInterferenceConsequence,
  getComplianceRate,
  getComplianceDescription,
  shouldGenerateDemand,
} from './InterferenceSystem';

// Owner Demand Generator
export {
  PlayerInfo,
  CoachInfo,
  ProspectInfo,
  DemandContext,
  selectDemandType,
  generateSignPlayerDemand,
  generateFireCoachDemand,
  generateDraftPlayerDemand,
  generateTradeForDemand,
  generateOtherDemand,
  generateDemand,
  getDemandUrgency,
  getDemandDisplayInfo,
  isDemandSatisfied,
} from './OwnerDemandGenerator';

// Owner Mood System
export {
  OwnerMood,
  MoodEventType,
  MoodEvent,
  OwnerMoodState,
  createOwnerMoodState,
  getMoodFromValue,
  getMoodDescription,
  createMoodEvent,
  processMoodEvent,
  getMoodTrend,
  getStreakDescription,
  applyMoodDecay,
  getRecentEventsSummary,
  getOwnerSentiment,
  shouldMakePublicStatement,
  generateOwnerStatement,
} from './OwnerMoodSystem';

// Ownership Change System
export {
  OwnershipChangeType,
  OwnershipChangeEvent,
  LeagueOwnershipState,
  createLeagueOwnershipState,
  generateOwnerName,
  calculateOwnershipChangeProbability,
  determineChangeType,
  generateChangeDescription,
  determineGMRetention,
  createNewOwner,
  processOwnershipChange,
  checkLeagueOwnershipChanges,
  getOwnershipChangeSummary,
  getTeamOwnershipHistory,
  initializeTeamOwnership,
} from './OwnershipChangeSystem';

// Patience Meter Manager
export {
  PatienceTrend,
  PatienceHistoryEntry,
  PatienceMeterState,
  PatienceViewModel,
  ImpactDescription,
  createPatienceMeterState,
  updatePatienceValue,
  startNewSeason,
  getCurrentSecurityLevel,
  calculateTrend,
  getTrendDescription,
  getWeeklyChange,
  getSeasonChange,
  getUrgencyLevel,
  isAtRisk,
  createPatienceViewModel,
  getImpactDescription,
  getDistanceToNextThreshold,
  getPointsToImprove,
  validatePatienceMeterState,
  calculateRecoveryModifier,
  calculateDeclineModifier,
  applyPersonalityModifiers,
  getPatienceSummary,
  syncWithOwner,
  createFromOwner,
} from './PatienceMeterManager';

// Patience Event Processor
export {
  PatienceEventType,
  PatienceEvent,
  PatienceEventResult,
  SeasonResultContext,
  getEventImpactRange,
  calculateEventImpact,
  processPatienceEvent,
  processMultipleEvents,
  generateSeasonEvents,
  processSeasonEnd,
  createDemandComplianceEvent,
  createPREvent,
  createPersonnelEvent,
  createGameResultEvent,
  calculateCumulativeImpact,
  getSupportedEventTypes,
  validatePatienceEvent,
} from './PatienceEventProcessor';

// Firing Mechanics
export {
  FiringReasonCategory,
  FiringReason,
  TenureStats,
  SeverancePackage,
  LegacyRating,
  FiringRecord,
  FiringContext,
  generateFiringReason,
  calculateSeverance,
  calculateLegacy,
  createDefaultTenureStats,
  updateTenureStats,
  recordCoachingChange,
  recordDraftPick,
  recordFreeAgentSigning,
  createFiringRecord,
  shouldFire,
  getLegacyDescription,
  validateTenureStats,
  validateFiringRecord,
} from './FiringMechanics';

// Owner Expectations System
export {
  TeamPhase,
  ExpectationUrgency,
  SeasonExpectation,
  SeasonGoal,
  LongTermExpectation,
  ExpectationTimeline,
  ExpectationsState,
  ExpectationHistory,
  ExpectationsViewModel,
  generateSeasonExpectations,
  generateLongTermExpectations,
  createExpectationsState,
  calculateUrgency,
  evaluateSeasonExpectations,
  advanceExpectations,
  createExpectationsViewModel,
  getCurrentYearGoal,
  validateExpectationsState,
  determineTeamPhase,
} from './OwnerExpectationsSystem';

// Career Record Tracker
export {
  SeasonSnapshot,
  TeamTenure,
  CareerAchievement,
  AchievementRecord,
  ReputationFactors,
  CareerRecord,
  ReputationTier,
  createCareerRecord,
  createDefaultReputationFactors,
  startNewTeam,
  recordSeason,
  recordFiring,
  recordResignation,
  recordUnemploymentYear,
  calculateReputationScore,
  updateReputationFromSeason,
  getReputationTier,
  getReputationTierDescription,
  getCareerSummary,
  getCurrentTenure,
  tenureStatsToTeamTenure,
  validateCareerRecord,
} from './CareerRecordTracker';

// Job Market Manager
export {
  OpeningReason,
  TeamSituation,
  InterestLevel,
  JobOpening,
  TeamInterest,
  JobMarketState,
  createJobMarketState,
  generateJobOpening,
  calculateTeamInterest,
  addOpening,
  fillOpening,
  calculateAllInterests,
  getAvailableOpenings,
  getInterestForOpening,
  getTeamSituationDescription,
  getOpeningDescription,
  simulateOtherHires,
  cleanupOldOpenings,
  updateReputation,
  validateJobMarketState,
} from './JobMarketManager';

// Interview System
export {
  InterviewStatus,
  ContractOffer,
  OwnerPreview,
  InterviewRecord,
  InterviewState,
  createInterviewState,
  requestInterview,
  conductInterview,
  generateOwnerPreview,
  acceptOffer,
  declineOffer,
  getPendingInterviews,
  getActiveOffers,
  processExpiredOffers,
  advanceInterviewWeek,
  getOfferSummary,
  validateInterviewState,
} from './InterviewSystem';

// Unemployment Year
export {
  UnemploymentEventType,
  UnemploymentEvent,
  ConsultantOpportunity,
  UnemploymentState,
  createUnemploymentState,
  startUnemploymentYear,
  generateMediaNarrative,
  simulateUnemploymentWeek,
  generateConsultantOpportunity,
  acceptConsultantOpportunity,
  completeConsultantJob,
  calculateUnemploymentReputationDecay,
  endUnemploymentYear,
  decideToRetire,
  getUnemploymentSummary,
  validateUnemploymentState,
} from './UnemploymentYear';

// Retirement System
export {
  LegacyTier,
  HallOfFameStatus,
  HighlightType,
  CareerHighlight,
  FinalCareerStats,
  CareerSummary,
  TeamLegacy,
  RetirementState,
  createRetirementState,
  initiateRetirement,
  generateCareerSummary,
  calculateLegacyScore,
  getRetirementHeadline,
  getLegacyTierDisplayName,
  getHallOfFameStatusDisplay,
  validateRetirementState,
} from './RetirementSystem';

// Player Progression System
export {
  ProgressionResult,
  ProgressionOptions,
  DevelopmentNewsItem,
  applyOffseasonProgression,
  applySkillChanges,
  processTeamProgression,
  generateDevelopmentNews,
} from './PlayerProgression';
