/**
 * Scouting System
 * Core scouting department, auto-scouting, focus scouting, accuracy tracking, and pro scouting
 */

// Scouting Department Manager
export {
  ScoutingPosition,
  TOTAL_SCOUTING_POSITIONS,
  SCOUTING_DEPARTMENT_STRUCTURE,
  RegionalAssignment,
  ScoutingDepartmentState,
  ScoutingVacancy,
  ScoutingDepartmentSummary,
  createScoutingDepartmentState,
  getDepartmentScouts,
  getScoutsByRole,
  getHeadScout,
  getScoutsForRegion,
  getPrimaryScoutForRegion,
  getScoutingVacancies,
  hireScout,
  fireScout,
  assignScoutToRegion,
  removeScoutFromRegion,
  updateScoutingBudget,
  advanceScoutingYear,
  getScoutingDepartmentSummary,
  hasMinimumScoutingStaff,
  getTotalDepartmentSalary,
  validateScoutingDepartmentState,
  renewScoutContract,
} from './ScoutingDepartmentManager';

// Auto-Scouting System
export {
  SkillRange,
  TraitVisibility,
  AutoScoutingReport,
  AutoScoutingConfig,
  DEFAULT_AUTO_SCOUTING_CONFIG,
  ProspectData,
  WeeklyScoutingResult,
  calculateAutoScoutSkillRange,
  calculateAutoScoutRoundRange,
  getVisibleTraitsForAutoScouting,
  generateAutoScoutingReport,
  processWeeklyAutoScouting,
  aggregateAutoScoutingReports,
  validateAutoScoutingReport,
  getAutoScoutReportQuality,
} from './AutoScoutingSystem';

// Focus Player System
export {
  CharacterAssessment,
  MedicalAssessment,
  SchemeFitAnalysis,
  InterviewInsights,
  FocusScoutingReport,
  FocusScoutingConfig,
  DEFAULT_FOCUS_SCOUTING_CONFIG,
  ExtendedProspectData,
  FocusScoutingProgress,
  getMaxFocusProspects,
  calculateFocusSkillRange,
  calculateFocusRoundRange,
  generateCharacterAssessment,
  generateMedicalAssessment,
  generateSchemeFitAnalysis,
  generateInterviewInsights,
  generateFocusScoutingReport,
  crossReferenceFocusReports,
  canAssignFocusPlayer,
  validateFocusScoutingReport,
} from './FocusPlayerSystem';

// Scout Accuracy System
export {
  AccuracyRevelationState,
  ScoutAccuracyViewModel,
  EvaluationResult,
  HitClassification,
  AccuracyBreakdown,
  createAccuracyRevelationState,
  recordScoutEvaluation,
  updateEvaluationsWithResults,
  advanceAccuracyYear,
  classifyEvaluation,
  getAccuracyBreakdown,
  getPositionAccuracy,
  hasStrengthAtPosition,
  hasWeaknessAtPosition,
  createScoutAccuracyViewModel,
  compareScoutAccuracy,
  getScoutsByAccuracy,
  getYearsUntilRevelation,
  hasPositionAccuracyData,
  getEvaluatedPositions,
  getScoutPositionTendencies,
} from './ScoutAccuracySystem';

// Pro Scouting System
export {
  PlayerStatus,
  VisibilityLevel,
  ContractInfo,
  PerformanceTrend,
  TradeValueAssessment,
  ProPlayerData,
  ProScoutingReport,
  ProScoutingConfig,
  DEFAULT_PRO_SCOUTING_CONFIG,
  getPlayerVisibility,
  calculateProScoutSkillRange,
  getVisibleProTraits,
  analyzePerformanceTrend,
  calculateTradeValue,
  generateProScoutingReport,
  compareProReports,
  identifyScoutingTargets,
  validateProScoutingReport,
} from './ProScoutingSystem';

// Scout Report Generator (PR-12)
export {
  ReportType,
  PhysicalMeasurements,
  DraftProjection,
  ConfidenceFactor,
  ReportConfidence,
  TraitInfo,
  ScoutReport,
  DisplayReport,
  ReportGenerationConfig,
  DEFAULT_REPORT_CONFIG,
  generateReportId,
  calculateDraftProjection,
  generateConfidenceFactors,
  calculateReportConfidence,
  convertTraitsToInfo,
  generateAutoScoutReport,
  generateFocusScoutReport,
  formatSkillRange,
  formatReportForDisplay,
  convertAutoReportToScoutReport,
  convertFocusReportToScoutReport,
  validateScoutReport,
  getReportQuality,
} from './ScoutReportGenerator';

// Report Confidence System (PR-12)
export {
  ScoutTendency,
  ScoutTendencyProfile,
  ConfidenceAdjustment,
  AggregatedConfidence,
  ConfidenceConfig,
  DEFAULT_CONFIDENCE_CONFIG,
  calculateBaseConfidence,
  calculateTimeConfidence,
  calculateRegionConfidenceModifier,
  calculatePositionConfidenceModifier,
  determineScoutTendency,
  createScoutTendencyProfile,
  calculateTendencyAdjustment,
  calculateConfidenceAdjustment,
  adjustRangeByConfidence,
  adjustRangesByConfidence,
  aggregateConfidence,
  getConfidenceDescription,
  calculateConfidenceImprovement,
  validateConfidence,
  calculateEnhancedConfidence,
} from './ReportConfidenceSystem';

// Draft Board Manager (PR-12)
export {
  DraftBoardProspect,
  DraftTier,
  DraftBoardState,
  DraftBoardSortOption,
  DraftBoardViewModel,
  DraftBoardProspectView,
  DirectorInput,
  createDraftBoardState,
  calculateConsensusRound,
  calculateAverageOverallRange,
  determineDraftTier,
  createDraftBoardProspect,
  addReportToBoard,
  addReportsToBoard,
  setUserRanking,
  removeUserRanking,
  setUserNotes,
  setUserTier,
  lockProspect,
  unlockProspect,
  addDirectorInput,
  setFilters,
  setSortOption,
  getSortedProspects,
  getDraftBoardView,
  removeProspect,
  finalizeDraftBoard,
  validateDraftBoardState,
  getProspectsNeedingScouting,
  getProspectsByPosition,
  getTopProspectsByTier,
} from './DraftBoardManager';

// Big Board Generator (PR-12)
export {
  NeedLevel,
  PositionalNeeds,
  ScoutReliability,
  ProspectRanking,
  BigBoard,
  BigBoardConfig,
  DEFAULT_BIG_BOARD_CONFIG,
  createDefaultPositionalNeeds,
  createScoutReliability,
  getScoutReliabilityWeight,
  calculateSkillScore,
  calculateConfidenceScore,
  calculateWeightedSkillScore,
  calculateNeedBonus,
  createProspectRanking,
  generateProspectRankings,
  generateNeedAdjustedRankings,
  generatePositionRankings,
  generateTierRankings,
  identifyBestValue,
  identifyRisers,
  identifyFallers,
  generateBigBoard,
  compareProspects,
  getPositionGroupRankings,
  validateBigBoard,
  getBigBoardSummary,
} from './BigBoardGenerator';

// Draft Recommendation System
export {
  ScoutDraftRecommendation,
  DraftPickRecommendations,
  generateScoutRecommendation,
  generatePickRecommendations,
  getAutoPickRecommendation,
} from './DraftRecommendationSystem';
