export {
  type PracticeFocusArea,
  type GamePlanEmphasis,
  type WeeklyGamePlan,
  type GamePlanModifiers,
  type OpponentAnalysis,
  type OpponentWeakness,
  type OpponentStrength,
  ALL_PRACTICE_FOCUS_AREAS,
  PRACTICE_FOCUS_LABELS,
  GAME_PLAN_EMPHASIS_LABELS,
  GAME_PLAN_EMPHASIS_DESCRIPTIONS,
  createDefaultGamePlan,
  updatePracticeFocus,
  setGamePlanEmphasis,
  confirmGamePlan,
  calculateGamePlanModifiers,
  analyzeOpponent,
  applyGamePlan,
} from './GamePlanManager';
