/**
 * Draft Module
 * Provides draft class generation, combine simulation, and pro day workouts
 */

// College Program Generator
export {
  ConferenceTier,
  Conference,
  CONFERENCE_TIERS,
  PrestigeTier,
  PRESTIGE_RANGES,
  CollegeProgram,
  ProgramType,
  CollegeProgramSummary,
  generateCollegeProgram,
  generateAllCollegePrograms,
  getProgramsByConference,
  getProgramsByConferenceTier,
  getProgramsByPrestigeTier,
  getRandomProgramByPrestige,
  getProgramById,
  getProgramsByState,
  incrementNflAlumni,
  validateCollegeProgram,
  getCollegeProgramSummary,
} from './CollegeProgramGenerator';

// Class Strength System
export {
  ClassStrength,
  CLASS_STRENGTH_DESCRIPTIONS,
  ClassStrengthModifiers,
  CLASS_STRENGTH_MODIFIERS,
  TierDistribution,
  BASE_TIER_DISTRIBUTION,
  PositionStrengthModifiers,
  DraftClassMeta,
  generateClassStrength,
  generateClassStrengthForYear,
  getClassStrengthModifiers,
  calculateTierDistribution,
  getProspectTier,
  applySkillModifier,
  generatePositionStrengthModifiers,
  getPositionModifier,
  createDraftClassMeta,
  createDraftClassMetaWithStrength,
  validateDraftClassMeta,
  getExpectedEliteCount,
  getExpectedStarterCount,
  getClassQualityLabel,
} from './ClassStrengthSystem';

// Prospect Entity
export {
  CollegeStats,
  PositionCollegeStats,
  QBCollegeStats,
  RBCollegeStats,
  WRCollegeStats,
  TECollegeStats,
  OLCollegeStats,
  DLCollegeStats,
  LBCollegeStats,
  DBCollegeStats,
  KPCollegeStats,
  CollegeAward,
  COLLEGE_AWARDS,
  CollegeInjury,
  DraftProjection,
  ProspectRanking,
  WorkoutStatus,
  Prospect,
  ProspectView,
  createEmptyCollegeStats,
  createProspect,
  updateCombineStatus,
  updateProDayStatus,
  addScoutReport,
  setProspectUserNotes,
  toggleProspectFlag,
  setProspectUserTier,
  updateConsensusProjection,
  updateUserProjection,
  addProspectRanking,
  getOverallRanking,
  getPositionRanking,
  validateProspect,
  getProspectDisplayName,
  getProspectPosition,
  hasRevealedPhysicals,
  getRevealedPhysicals,
  createProspectView,
} from './Prospect';

// Draft Class Generator
export {
  POSITION_WEIGHTS,
  DraftClassConfig,
  DEFAULT_DRAFT_CLASS_CONFIG,
  DraftClass,
  DraftClassSummary,
  generateDraftClass,
  getDraftClassSummary,
  getProspectsByPosition,
  getTopProspects,
  validateDraftClass,
} from './DraftClassGenerator';

// Combine Simulator
export {
  CombineWorkoutResults,
  InterviewImpression,
  MedicalEvaluation,
  MedicalGrade,
  MedicalConcern,
  CombineResults,
  OfficialMeasurements,
  CombineGrade,
  CombineConfig,
  DEFAULT_COMBINE_CONFIG,
  CombineSimulationResults,
  CombineSummary,
  selectCombineInvites,
  simulateCombineForProspect,
  simulateCombine,
  getCombineResultsForProspect,
  validateCombineResults,
} from './CombineSimulator';

// Pro Day Simulator
export {
  ProDayType,
  ProDayAttendance,
  PositionWorkoutResults,
  ProDayResults,
  ProDayConfig,
  DEFAULT_PRO_DAY_CONFIG,
  ProDaySimulationResults,
  ProDaySummary,
  simulateProDayForProspect,
  simulateProDays,
  getProDayResultsForProspect,
  validateProDayResults,
} from './ProDaySimulator';
