/**
 * Draft Module
 * Provides draft class generation, combine simulation, and pro day workouts
 */

// College Program Generator
export {
  ConferenceTier,
  Conference,
  CONFERENCE_TIERS,
  PrestigeTier,
  PRESTIGE_RANGES,
  CollegeProgram,
  ProgramType,
  CollegeProgramSummary,
  generateCollegeProgram,
  generateAllCollegePrograms,
  getProgramsByConference,
  getProgramsByConferenceTier,
  getProgramsByPrestigeTier,
  getRandomProgramByPrestige,
  getProgramById,
  getProgramsByState,
  incrementNflAlumni,
  validateCollegeProgram,
  getCollegeProgramSummary,
} from './CollegeProgramGenerator';

// Class Strength System
export {
  ClassStrength,
  CLASS_STRENGTH_DESCRIPTIONS,
  ClassStrengthModifiers,
  CLASS_STRENGTH_MODIFIERS,
  TierDistribution,
  BASE_TIER_DISTRIBUTION,
  PositionStrengthModifiers,
  DraftClassMeta,
  generateClassStrength,
  generateClassStrengthForYear,
  getClassStrengthModifiers,
  calculateTierDistribution,
  getProspectTier,
  applySkillModifier,
  generatePositionStrengthModifiers,
  getPositionModifier,
  createDraftClassMeta,
  createDraftClassMetaWithStrength,
  validateDraftClassMeta,
  getExpectedEliteCount,
  getExpectedStarterCount,
  getClassQualityLabel,
} from './ClassStrengthSystem';

// Prospect Entity
export {
  CollegeStats,
  PositionCollegeStats,
  QBCollegeStats,
  RBCollegeStats,
  WRCollegeStats,
  TECollegeStats,
  OLCollegeStats,
  DLCollegeStats,
  LBCollegeStats,
  DBCollegeStats,
  KPCollegeStats,
  CollegeAward,
  COLLEGE_AWARDS,
  CollegeInjury,
  DraftProjection,
  ProspectRanking,
  WorkoutStatus,
  Prospect,
  ProspectView,
  createEmptyCollegeStats,
  createProspect,
  updateCombineStatus,
  updateProDayStatus,
  addScoutReport,
  setProspectUserNotes,
  toggleProspectFlag,
  setProspectUserTier,
  updateConsensusProjection,
  updateUserProjection,
  addProspectRanking,
  getOverallRanking,
  getPositionRanking,
  validateProspect,
  getProspectDisplayName,
  getProspectPosition,
  hasRevealedPhysicals,
  getRevealedPhysicals,
  createProspectView,
} from './Prospect';

// Draft Class Generator
export {
  POSITION_WEIGHTS,
  DraftClassConfig,
  DEFAULT_DRAFT_CLASS_CONFIG,
  DraftClass,
  DraftClassSummary,
  generateDraftClass,
  getDraftClassSummary,
  getProspectsByPosition,
  getTopProspects,
  validateDraftClass,
} from './DraftClassGenerator';

// Combine Simulator
export {
  CombineWorkoutResults,
  InterviewImpression,
  MedicalEvaluation,
  MedicalGrade,
  MedicalConcern,
  CombineResults,
  OfficialMeasurements,
  CombineGrade,
  CombineConfig,
  DEFAULT_COMBINE_CONFIG,
  CombineSimulationResults,
  CombineSummary,
  selectCombineInvites,
  simulateCombineForProspect,
  simulateCombine,
  getCombineResultsForProspect,
  validateCombineResults,
} from './CombineSimulator';

// Pro Day Simulator
export {
  ProDayType,
  ProDayAttendance,
  PositionWorkoutResults,
  ProDayResults,
  ProDayConfig,
  DEFAULT_PRO_DAY_CONFIG,
  ProDaySimulationResults,
  ProDaySummary,
  simulateProDayForProspect,
  simulateProDays,
  getProDayResultsForProspect,
  validateProDayResults,
} from './ProDaySimulator';

// Draft Order Manager
export {
  MAX_FUTURE_TRADE_YEARS,
  MAX_COMP_PICKS_PER_ROUND,
  MAX_COMP_PICKS_TOTAL,
  FATransaction,
  CompPickCalculation,
  DraftYearState,
  DraftOrderState,
  createDraftOrderState,
  createDraftYearState,
  getTeamPicks,
  getPicksByRound,
  executeTrade,
  recordFATransaction,
  calculateCompensatoryPicks,
  awardCompensatoryPicks,
  setDraftOrderFromStandings,
  getDraftOrder,
  getNextPick,
  canTradePick,
  finalizeDraftYear,
  advanceYear,
  getTotalPicksForYear,
  validateDraftOrderState,
  validateDraftYearState,
  DraftCapitalSummary,
  getTeamDraftCapitalSummary,
} from './DraftOrderManager';

// Trade Value Calculator
export {
  TradeAssessment,
  TradeEvaluation,
  TradeProposal,
  evaluateTrade,
  wouldAIAcceptTrade,
  suggestTradeAdditions,
  getPickTierDescription,
  comparePicksQualitative,
  validateTradeEvaluation,
  estimateOverallFromRound,
} from './TradeValueCalculator';

// AI Draft Strategy
export {
  DraftPhilosophy,
  NeedLevel,
  TeamNeeds,
  AIDraftProfile,
  AITradeOffer,
  AIPickDecision,
  assessTeamNeeds,
  createAIDraftProfile,
  generateRandomPhilosophy,
  rankProspectsForTeam,
  getAITopPick,
  shouldConsiderTradeUp,
  shouldConsiderTradeDown,
  generateTradeOffer,
  evaluateTradeOffer,
  makeAIPickDecision,
  validateAIDraftProfile,
  validateTeamNeeds,
} from './AIDraftStrategy';

// Draft Room Simulator
export {
  DraftTimerConfig,
  DEFAULT_TIMER_CONFIG,
  DraftPickResult,
  TradeResult,
  RoundStatus,
  DraftStatus,
  CurrentPickState,
  PendingTradeOffer,
  DraftRoomState,
  createDraftRoomState,
  startDraft,
  getTimeForPick,
  makeUserPick,
  processAIPick,
  continueAfterRoundBreak,
  pauseDraft,
  resumeDraft,
  proposeTradeToAI,
  receiveAITradeOffer,
  acceptTradeOffer,
  rejectTradeOffer,
  updateTimer,
  getRoundStatus,
  getAllRoundStatuses,
  DraftSummary,
  getDraftSummary,
  generatePotentialTradeOffers,
  clearExpiredOffers,
  validateDraftRoomState,
} from './DraftRoomSimulator';

// Rookie Contract Generator
export {
  RookieContract,
  YearlyContractBreakdown,
  FifthYearOption,
  ROOKIE_MINIMUM_SALARY,
  getSlotValues,
  calculateYearlyBreakdown,
  generateRookieContract,
  exerciseFifthYearOption,
  declineFifthYearOption,
  getCapHitForYear,
  getRemainingYears,
  getRemainingGuaranteed,
  getDeadCap,
  ContractSummary,
  getContractSummary,
  validateRookieContract,
} from './RookieContractGenerator';

// UDFA System
export {
  UDFA_BONUS_BUDGET,
  MAX_UDFA_SIGNINGS,
  UDFAInterestLevel,
  TeamUDFAInterest,
  UDFAOffer,
  UDFAPoolState,
  UDFASigningResult,
  createUDFAPool,
  getProspectCompetition,
  getTopUDFAs,
  getUDFAsByPosition,
  attemptUDFASigning,
  simulateAISignings,
  getUserRemainingBudget,
  getUserSignedUDFAs,
  getTeamSignedUDFAs,
  createUDFAOffer,
  UDFAPoolSummary,
  getUDFAPoolSummary,
  validateUDFAPoolState,
} from './UDFASystem';
