/**
 * Depth Chart Types
 * Core type definitions for the realistic depth chart system
 */

import { Position } from '../models/player/Position';
import { DepthChartSlot } from './DepthChartSlots';
import { OffensivePersonnel, DefensivePackage } from './FormationPackages';

/**
 * Individual depth chart assignment
 */
export interface DepthChartAssignment {
  slot: DepthChartSlot;
  playerId: string;
  isLocked: boolean; // User locked this assignment (won't auto-update)
  outOfPosition: boolean; // Player's primary position doesn't match slot
  effectivenessRating: number; // How well they fit this slot (0-100)
}

/**
 * Formation-specific override
 * Allows different players in specific formations
 */
export interface FormationOverride {
  package: OffensivePersonnel | DefensivePackage | string;
  slot: DepthChartSlot;
  playerId: string;
}

/**
 * Complete team depth chart
 */
export interface DepthChart {
  teamId: string;
  version: 2; // Version 2 of the depth chart system

  // Standard depth assignments
  assignments: DepthChartAssignment[];

  // Formation-specific overrides (e.g., different RB for 3rd down)
  formationOverrides: FormationOverride[];

  // Metadata
  autoGenerated: boolean;
  lastUpdated: number;
  lastAutoSortDate: number | null;
}

/**
 * Legacy depth chart format (version 1)
 * Used for migration
 */
export interface LegacyDepthChart {
  teamId: string;
  entries: Array<{
    position: Position;
    playerId: string;
    depth: 1 | 2 | 3;
  }>;
  autoGenerated: boolean;
  lastUpdated: number;
}

/**
 * UI view model for a position group
 */
export interface DepthChartGroupView {
  groupName: string;
  subcategories: DepthChartSubcategoryView[];
}

/**
 * UI view model for a subcategory (e.g., "Wide Receivers")
 */
export interface DepthChartSubcategoryView {
  name: string;
  slots: DepthChartSlotView[];
}

/**
 * UI view model for a single slot
 */
export interface DepthChartSlotView {
  slot: DepthChartSlot;
  displayName: string;
  shortName: string;
  assignment: DepthChartAssignment | null;
  isRequired: boolean;
  isSpecialist: boolean;
  eligiblePlayerCount: number;
}

/**
 * Player depth chart status
 */
export interface PlayerDepthStatus {
  playerId: string;
  primarySlot: DepthChartSlot | null;
  secondarySlots: DepthChartSlot[];
  isStarter: boolean;
  isOnDepthChart: boolean;
}

/**
 * Depth chart validation result
 */
export interface DepthChartValidation {
  isValid: boolean;
  missingRequiredSlots: DepthChartSlot[];
  emptySlots: DepthChartSlot[];
  outOfPositionPlayers: Array<{
    playerId: string;
    slot: DepthChartSlot;
    playerPosition: Position;
  }>;
  duplicatePlayers: Array<{
    playerId: string;
    slots: DepthChartSlot[];
  }>;
  warnings: string[];
}

/**
 * Auto-fill result
 */
export interface AutoFillResult {
  depthChart: DepthChart;
  assignmentsChanged: number;
  unfilledSlots: DepthChartSlot[];
  warnings: string[];
}

/**
 * Depth chart comparison for showing changes
 */
export interface DepthChartDiff {
  added: DepthChartAssignment[];
  removed: DepthChartAssignment[];
  changed: Array<{
    slot: DepthChartSlot;
    oldPlayerId: string;
    newPlayerId: string;
  }>;
}

/**
 * Options for auto-generating depth chart
 */
export interface DepthChartGenerationOptions {
  preserveLockedAssignments: boolean;
  fillSpecialists: boolean;
  preferExperience: boolean;
  scheme?: 'balanced' | 'passing' | 'rushing';
}

/**
 * Roster slot requirements for game simulation
 */
export interface GameLineup {
  offense: Map<DepthChartSlot, string>;
  defense: Map<DepthChartSlot, string>;
  specialTeams: Map<DepthChartSlot, string>;
}

/**
 * Package-specific lineup
 */
export interface PackageLineup {
  packageId: string;
  packageName: string;
  players: Map<DepthChartSlot, string>;
}
